# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G://Projects/_tools/_maya/fossil\pdil\tool\fossil/ui/rigToolUI.ui',
# licensing of 'G://Projects/_tools/_maya/fossil\pdil\tool\fossil/ui/rigToolUI.ui' applies.
#
# Created: Tue Jul 13 00:37:35 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from QT_PDIL_vendored import QtCompat, QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 1050)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.jointCount = QtWidgets.QSpinBox(self.widget_4)
        self.jointCount.setMinimum(1)
        self.jointCount.setObjectName("jointCount")
        self.gridLayout.addWidget(self.jointCount, 0, 0, 1, 1)
        self.buildBonesBtn = QtWidgets.QPushButton(self.widget_4)
        self.buildBonesBtn.setObjectName("buildBonesBtn")
        self.gridLayout.addWidget(self.buildBonesBtn, 1, 1, 1, 1)
        self.buildRigBtn = QtWidgets.QPushButton(self.widget_4)
        self.buildRigBtn.setObjectName("buildRigBtn")
        self.gridLayout.addWidget(self.buildRigBtn, 1, 2, 1, 1)
        self.cardJointNames = QtWidgets.QLineEdit(self.widget_4)
        self.cardJointNames.setObjectName("cardJointNames")
        self.gridLayout.addWidget(self.cardJointNames, 0, 1, 1, 2)
        self.selectAllBtn = QtWidgets.QPushButton(self.widget_4)
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.gridLayout.addWidget(self.selectAllBtn, 1, 0, 1, 1)
        self.deleteRigBtn = QtWidgets.QPushButton(self.widget_4)
        self.deleteRigBtn.setObjectName("deleteRigBtn")
        self.gridLayout.addWidget(self.deleteRigBtn, 2, 2, 1, 1)
        self.deleteBonesBtn = QtWidgets.QPushButton(self.widget_4)
        self.deleteBonesBtn.setObjectName("deleteBonesBtn")
        self.gridLayout.addWidget(self.deleteBonesBtn, 2, 1, 1, 1)
        self.saveModsBtn = QtWidgets.QPushButton(self.widget_4)
        self.saveModsBtn.setObjectName("saveModsBtn")
        self.gridLayout.addWidget(self.saveModsBtn, 1, 3, 1, 1)
        self.restoreModsBtn = QtWidgets.QPushButton(self.widget_4)
        self.restoreModsBtn.setObjectName("restoreModsBtn")
        self.gridLayout.addWidget(self.restoreModsBtn, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 4, 1, 1)
        self.makeCardBtn = QtWidgets.QPushButton(self.widget_4)
        self.makeCardBtn.setObjectName("makeCardBtn")
        self.gridLayout.addWidget(self.makeCardBtn, 0, 5, 1, 1)
        self.rebuildProxyBtn = QtWidgets.QPushButton(self.widget_4)
        self.rebuildProxyBtn.setObjectName("rebuildProxyBtn")
        self.gridLayout.addWidget(self.rebuildProxyBtn, 0, 6, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.restoreContainer = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restoreContainer.sizePolicy().hasHeightForWidth())
        self.restoreContainer.setSizePolicy(sizePolicy)
        self.restoreContainer.setMinimumSize(QtCore.QSize(30, 0))
        self.restoreContainer.setObjectName("restoreContainer")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.restoreContainer)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setContentsMargins(-1, -1, -1, 3)
        self.layout.setObjectName("layout")
        self.constraintsRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.constraintsRestore.setObjectName("constraintsRestore")
        self.layout.addWidget(self.constraintsRestore, 0, 2, 1, 1)
        self.lockedAttrsRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.lockedAttrsRestore.setObjectName("lockedAttrsRestore")
        self.layout.addWidget(self.lockedAttrsRestore, 1, 2, 1, 1)
        self.spacesRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.spacesRestore.setObjectName("spacesRestore")
        self.layout.addWidget(self.spacesRestore, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.restoreContainer)
        self.pushButton_3.setObjectName("pushButton_3")
        self.layout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.visGroupRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.visGroupRestore.setObjectName("visGroupRestore")
        self.layout.addWidget(self.visGroupRestore, 1, 0, 1, 1)
        self.connectionsRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.connectionsRestore.setObjectName("connectionsRestore")
        self.layout.addWidget(self.connectionsRestore, 0, 1, 1, 1)
        self.setDrivenRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.setDrivenRestore.setObjectName("setDrivenRestore")
        self.layout.addWidget(self.setDrivenRestore, 1, 1, 1, 1)
        self.customAttrsRestore = QtWidgets.QPushButton(self.restoreContainer)
        self.customAttrsRestore.setObjectName("customAttrsRestore")
        self.layout.addWidget(self.customAttrsRestore, 3, 1, 1, 1)
        self.horizontalLayout_13.addLayout(self.layout)
        self.horizontalLayout_6.addWidget(self.restoreContainer)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.cardLister = CardLister(self.widget_4)
        self.cardLister.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.cardLister.setObjectName("cardLister")
        self.cardLister.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.cardLister)
        self.widget_5 = QtWidgets.QWidget(self.splitter)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mergeCardBtn = QtWidgets.QPushButton(self.widget_5)
        self.mergeCardBtn.setObjectName("mergeCardBtn")
        self.gridLayout_2.addWidget(self.mergeCardBtn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 4, 1, 1)
        self.splitCardBtn = QtWidgets.QPushButton(self.widget_5)
        self.splitCardBtn.setObjectName("splitCardBtn")
        self.gridLayout_2.addWidget(self.splitCardBtn, 0, 3, 1, 1)
        self.addCardIkButton = QtWidgets.QPushButton(self.widget_5)
        self.addCardIkButton.setObjectName("addCardIkButton")
        self.gridLayout_2.addWidget(self.addCardIkButton, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.duplicateCardBtn = QtWidgets.QPushButton(self.widget_5)
        self.duplicateCardBtn.setObjectName("duplicateCardBtn")
        self.gridLayout_2.addWidget(self.duplicateCardBtn, 0, 1, 1, 1)
        self.remCardIkButton = QtWidgets.QPushButton(self.widget_5)
        self.remCardIkButton.setObjectName("remCardIkButton")
        self.gridLayout_2.addWidget(self.remCardIkButton, 0, 6, 1, 1)
        self.insertJointBtn = QtWidgets.QPushButton(self.widget_5)
        self.insertJointBtn.setObjectName("insertJointBtn")
        self.gridLayout_2.addWidget(self.insertJointBtn, 1, 1, 1, 1)
        self.addTipBtn = QtWidgets.QPushButton(self.widget_5)
        self.addTipBtn.setObjectName("addTipBtn")
        self.gridLayout_2.addWidget(self.addTipBtn, 1, 2, 1, 1)
        self.deleteJointBtn = QtWidgets.QPushButton(self.widget_5)
        self.deleteJointBtn.setObjectName("deleteJointBtn")
        self.gridLayout_2.addWidget(self.deleteJointBtn, 1, 3, 1, 1)
        self.customUpBtn = QtWidgets.QPushButton(self.widget_5)
        self.customUpBtn.setObjectName("customUpBtn")
        self.gridLayout_2.addWidget(self.customUpBtn, 1, 5, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.jointLister = JointLister(self.widget_5)
        self.jointLister.setColumnCount(6)
        self.jointLister.setObjectName("jointLister")
        self.jointLister.setColumnCount(6)
        self.jointLister.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.jointLister)
        self.verticalLayout_3.addWidget(self.splitter)
        self.propertyLayout = QtWidgets.QWidget(self.splitter_2)
        self.propertyLayout.setMaximumSize(QtCore.QSize(403, 16777215))
        self.propertyLayout.setObjectName("propertyLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.propertyLayout)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.propertyLayout)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 95))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 95))
        self.widget_8.setObjectName("widget_8")
        self.cardName = QtWidgets.QLabel(self.widget_8)
        self.cardName.setGeometry(QtCore.QRect(10, 0, 151, 20))
        self.cardName.setText("")
        self.cardName.setObjectName("cardName")
        self.cardType = QtWidgets.QLabel(self.widget_8)
        self.cardType.setGeometry(QtCore.QRect(180, 0, 81, 20))
        self.cardType.setText("")
        self.cardType.setObjectName("cardType")
        self.cardDescription = QtWidgets.QLabel(self.widget_8)
        self.cardDescription.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.cardDescription.setText("")
        self.cardDescription.setWordWrap(True)
        self.cardDescription.setObjectName("cardDescription")
        self.verticalLayout_4.addWidget(self.widget_8)
        self.cardParams = CardParams(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardParams.sizePolicy().hasHeightForWidth())
        self.cardParams.setSizePolicy(sizePolicy)
        self.cardParams.setMinimumSize(QtCore.QSize(0, 250))
        self.cardParams.setObjectName("cardParams")
        self.cardParams.setColumnCount(2)
        self.cardParams.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(1, item)
        self.cardParams.horizontalHeader().setVisible(False)
        self.cardParams.horizontalHeader().setStretchLastSection(True)
        self.cardParams.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.cardParams)
        self.verticalLayout_5.addWidget(self.widget_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.rigStateContainer = QtWidgets.QWidget(self.propertyLayout)
        self.rigStateContainer.setObjectName("rigStateContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rigStateContainer)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.updateRigState = QtWidgets.QPushButton(self.rigStateContainer)
        self.updateRigState.setObjectName("updateRigState")
        self.verticalLayout_6.addWidget(self.updateRigState)
        self.rigStateTab = QtWidgets.QTabWidget(self.rigStateContainer)
        self.rigStateTab.setTabPosition(QtWidgets.QTabWidget.West)
        self.rigStateTab.setDocumentMode(False)
        self.rigStateTab.setObjectName("rigStateTab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.space_save = QtWidgets.QPushButton(self.tab_2)
        self.space_save.setObjectName("space_save")
        self.horizontalLayout_14.addWidget(self.space_save)
        self.space_load = QtWidgets.QPushButton(self.tab_2)
        self.space_load.setObjectName("space_load")
        self.horizontalLayout_14.addWidget(self.space_load)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.spacesField = QtWidgets.QTextEdit(self.tab_2)
        self.spacesField.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.spacesField.setObjectName("spacesField")
        self.verticalLayout_11.addWidget(self.spacesField)
        self.rigStateTab.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.vis_save = QtWidgets.QPushButton(self.tab_8)
        self.vis_save.setObjectName("vis_save")
        self.horizontalLayout_15.addWidget(self.vis_save)
        self.vis_load = QtWidgets.QPushButton(self.tab_8)
        self.vis_load.setObjectName("vis_load")
        self.horizontalLayout_15.addWidget(self.vis_load)
        self.verticalLayout_19.addLayout(self.horizontalLayout_15)
        self.visGroupField = QtWidgets.QTextEdit(self.tab_8)
        self.visGroupField.setObjectName("visGroupField")
        self.verticalLayout_19.addWidget(self.visGroupField)
        self.rigStateTab.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.shape_save = QtWidgets.QPushButton(self.tab_6)
        self.shape_save.setObjectName("shape_save")
        self.horizontalLayout_16.addWidget(self.shape_save)
        self.verticalLayout_20.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.shape_local_load = QtWidgets.QPushButton(self.tab_6)
        self.shape_local_load.setObjectName("shape_local_load")
        self.horizontalLayout_17.addWidget(self.shape_local_load)
        self.shape_world_load = QtWidgets.QPushButton(self.tab_6)
        self.shape_world_load.setObjectName("shape_world_load")
        self.horizontalLayout_17.addWidget(self.shape_world_load)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.shapesField = QtWidgets.QTextEdit(self.tab_6)
        self.shapesField.setObjectName("shapesField")
        self.verticalLayout_20.addWidget(self.shapesField)
        self.rigStateTab.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.constraints_save = QtWidgets.QPushButton(self.tab_7)
        self.constraints_save.setObjectName("constraints_save")
        self.horizontalLayout_18.addWidget(self.constraints_save)
        self.constraints_load = QtWidgets.QPushButton(self.tab_7)
        self.constraints_load.setObjectName("constraints_load")
        self.horizontalLayout_18.addWidget(self.constraints_load)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.constraintsField = QtWidgets.QTextEdit(self.tab_7)
        self.constraintsField.setObjectName("constraintsField")
        self.verticalLayout_21.addWidget(self.constraintsField)
        self.rigStateTab.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.connections_save = QtWidgets.QPushButton(self.tab_5)
        self.connections_save.setObjectName("connections_save")
        self.horizontalLayout_19.addWidget(self.connections_save)
        self.connections_load = QtWidgets.QPushButton(self.tab_5)
        self.connections_load.setObjectName("connections_load")
        self.horizontalLayout_19.addWidget(self.connections_load)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        self.connectionsField = QtWidgets.QTextEdit(self.tab_5)
        self.connectionsField.setObjectName("connectionsField")
        self.verticalLayout_22.addWidget(self.connectionsField)
        self.rigStateTab.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.driven_save = QtWidgets.QPushButton(self.tab_9)
        self.driven_save.setObjectName("driven_save")
        self.horizontalLayout_20.addWidget(self.driven_save)
        self.driven_load = QtWidgets.QPushButton(self.tab_9)
        self.driven_load.setObjectName("driven_load")
        self.horizontalLayout_20.addWidget(self.driven_load)
        self.verticalLayout_23.addLayout(self.horizontalLayout_20)
        self.setDrivenField = QtWidgets.QTextEdit(self.tab_9)
        self.setDrivenField.setObjectName("setDrivenField")
        self.verticalLayout_23.addWidget(self.setDrivenField)
        self.rigStateTab.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.custom_save = QtWidgets.QPushButton(self.tab_10)
        self.custom_save.setObjectName("custom_save")
        self.horizontalLayout_21.addWidget(self.custom_save)
        self.custom_load = QtWidgets.QPushButton(self.tab_10)
        self.custom_load.setObjectName("custom_load")
        self.horizontalLayout_21.addWidget(self.custom_load)
        self.verticalLayout_24.addLayout(self.horizontalLayout_21)
        self.customAttrsField = QtWidgets.QTextEdit(self.tab_10)
        self.customAttrsField.setObjectName("customAttrsField")
        self.verticalLayout_24.addWidget(self.customAttrsField)
        self.rigStateTab.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.locked_save = QtWidgets.QPushButton(self.tab_11)
        self.locked_save.setObjectName("locked_save")
        self.horizontalLayout_22.addWidget(self.locked_save)
        self.locked_load = QtWidgets.QPushButton(self.tab_11)
        self.locked_load.setObjectName("locked_load")
        self.horizontalLayout_22.addWidget(self.locked_load)
        self.verticalLayout_25.addLayout(self.horizontalLayout_22)
        self.lockedAttrsField = QtWidgets.QTextEdit(self.tab_11)
        self.lockedAttrsField.setObjectName("lockedAttrsField")
        self.verticalLayout_25.addWidget(self.lockedAttrsField)
        self.rigStateTab.addTab(self.tab_11, "")
        self.verticalLayout_6.addWidget(self.rigStateTab)
        self.verticalLayout_5.addWidget(self.rigStateContainer)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.controller_edit = QtWidgets.QWidget()
        self.controller_edit.setObjectName("controller_edit")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.controller_edit)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(25, -1, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.controller_edit)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.scrollArea = QtWidgets.QScrollArea(self.controller_edit)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 341, 97))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shape_chooser = QtWidgets.QGridLayout()
        self.shape_chooser.setObjectName("shape_chooser")
        self.gridLayout_4.addLayout(self.shape_chooser, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_14.addWidget(self.scrollArea)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.controller_edit)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.surfaceColorGrid = QtWidgets.QGridLayout()
        self.surfaceColorGrid.setObjectName("surfaceColorGrid")
        self.verticalLayout_15.addLayout(self.surfaceColorGrid)
        self.surfaceColorLayout = QtWidgets.QGridLayout()
        self.surfaceColorLayout.setContentsMargins(-1, -1, -1, 55)
        self.surfaceColorLayout.setObjectName("surfaceColorLayout")
        self.verticalLayout_15.addLayout(self.surfaceColorLayout)
        self.label_12 = QtWidgets.QLabel(self.controller_edit)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.curveColorGrid = QtWidgets.QGridLayout()
        self.curveColorGrid.setObjectName("curveColorGrid")
        self.verticalLayout_15.addLayout(self.curveColorGrid)
        self.curveColorLayout = QtWidgets.QGridLayout()
        self.curveColorLayout.setObjectName("curveColorLayout")
        self.verticalLayout_15.addLayout(self.curveColorLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_15)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.controller_edit)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.controller_edit)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 1)
        self.copyShapes = QtWidgets.QPushButton(self.controller_edit)
        self.copyShapes.setObjectName("copyShapes")
        self.gridLayout_3.addWidget(self.copyShapes, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.controller_edit)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.select_cvs = QtWidgets.QPushButton(self.controller_edit)
        self.select_cvs.setObjectName("select_cvs")
        self.gridLayout_3.addWidget(self.select_cvs, 1, 2, 1, 1)
        self.copyToCBBtn = QtWidgets.QPushButton(self.controller_edit)
        self.copyToCBBtn.setObjectName("copyToCBBtn")
        self.gridLayout_3.addWidget(self.copyToCBBtn, 1, 1, 1, 1)
        self.pasteLocalBtn = QtWidgets.QPushButton(self.controller_edit)
        self.pasteLocalBtn.setObjectName("pasteLocalBtn")
        self.gridLayout_3.addWidget(self.pasteLocalBtn, 2, 1, 1, 1)
        self.pasteWorldBtn = QtWidgets.QPushButton(self.controller_edit)
        self.pasteWorldBtn.setObjectName("pasteWorldBtn")
        self.gridLayout_3.addWidget(self.pasteWorldBtn, 3, 1, 1, 1)
        self.select_band_edge_1 = QtWidgets.QPushButton(self.controller_edit)
        self.select_band_edge_1.setObjectName("select_band_edge_1")
        self.gridLayout_3.addWidget(self.select_band_edge_1, 3, 2, 1, 1)
        self.mirrorShapes = QtWidgets.QPushButton(self.controller_edit)
        self.mirrorShapes.setObjectName("mirrorShapes")
        self.gridLayout_3.addWidget(self.mirrorShapes, 2, 0, 1, 1)
        self.mirrorSide = QtWidgets.QPushButton(self.controller_edit)
        self.mirrorSide.setObjectName("mirrorSide")
        self.gridLayout_3.addWidget(self.mirrorSide, 3, 0, 1, 1)
        self.select_pin_head = QtWidgets.QPushButton(self.controller_edit)
        self.select_pin_head.setObjectName("select_pin_head")
        self.gridLayout_3.addWidget(self.select_pin_head, 2, 2, 1, 1)
        self.select_band_edge_2 = QtWidgets.QPushButton(self.controller_edit)
        self.select_band_edge_2.setObjectName("select_band_edge_2")
        self.gridLayout_3.addWidget(self.select_band_edge_2, 4, 2, 1, 1)
        self.copyColor = QtWidgets.QPushButton(self.controller_edit)
        self.copyColor.setObjectName("copyColor")
        self.gridLayout_3.addWidget(self.copyColor, 4, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.label_9 = QtWidgets.QLabel(self.controller_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.minus_ten = QtWidgets.QPushButton(self.controller_edit)
        self.minus_ten.setObjectName("minus_ten")
        self.horizontalLayout_11.addWidget(self.minus_ten)
        self.minus_one = QtWidgets.QPushButton(self.controller_edit)
        self.minus_one.setObjectName("minus_one")
        self.horizontalLayout_11.addWidget(self.minus_one)
        self.plus_one = QtWidgets.QPushButton(self.controller_edit)
        self.plus_one.setObjectName("plus_one")
        self.horizontalLayout_11.addWidget(self.plus_one)
        self.plus_ten = QtWidgets.QPushButton(self.controller_edit)
        self.plus_ten.setObjectName("plus_ten")
        self.horizontalLayout_11.addWidget(self.plus_ten)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.label_10 = QtWidgets.QLabel(self.controller_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rot_local_y = QtWidgets.QPushButton(self.controller_edit)
        self.rot_local_y.setObjectName("rot_local_y")
        self.gridLayout_5.addWidget(self.rot_local_y, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.controller_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.controller_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        self.rot_world_x = QtWidgets.QPushButton(self.controller_edit)
        self.rot_world_x.setObjectName("rot_world_x")
        self.gridLayout_5.addWidget(self.rot_world_x, 1, 1, 1, 1)
        self.rot_local_x = QtWidgets.QPushButton(self.controller_edit)
        self.rot_local_x.setObjectName("rot_local_x")
        self.gridLayout_5.addWidget(self.rot_local_x, 1, 0, 1, 1)
        self.rot_world_y = QtWidgets.QPushButton(self.controller_edit)
        self.rot_world_y.setObjectName("rot_world_y")
        self.gridLayout_5.addWidget(self.rot_world_y, 2, 1, 1, 1)
        self.rot_local_z = QtWidgets.QPushButton(self.controller_edit)
        self.rot_local_z.setObjectName("rot_local_z")
        self.gridLayout_5.addWidget(self.rot_local_z, 3, 0, 1, 1)
        self.rot_world_z = QtWidgets.QPushButton(self.controller_edit)
        self.rot_world_z.setObjectName("rot_world_z")
        self.gridLayout_5.addWidget(self.rot_world_z, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.controlCardList = QtWidgets.QTreeWidget(self.controller_edit)
        self.controlCardList.setObjectName("controlCardList")
        self.controlCardList.headerItem().setText(0, "1")
        self.controlCardList.header().setVisible(False)
        self.horizontalLayout_9.addWidget(self.controlCardList)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.shapeDebug = QtWidgets.QTextEdit(self.controller_edit)
        self.shapeDebug.setEnabled(True)
        self.shapeDebug.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.shapeDebug.setObjectName("shapeDebug")
        self.verticalLayout_13.addWidget(self.shapeDebug)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.controller_edit, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.visGroups = QtWidgets.QListWidget(self.tab_4)
        self.visGroups.setGeometry(QtCore.QRect(10, 10, 256, 381))
        self.visGroups.setObjectName("visGroups")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(280, 10, 341, 381))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.unequipVisControl = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.unequipVisControl.setObjectName("unequipVisControl")
        self.verticalLayout_9.addWidget(self.unequipVisControl)
        self.equipVisControl = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.equipVisControl.setObjectName("equipVisControl")
        self.verticalLayout_9.addWidget(self.equipVisControl)
        self.pruneVisGroups = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pruneVisGroups.setObjectName("pruneVisGroups")
        self.verticalLayout_9.addWidget(self.pruneVisGroups)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9.addWidget(self.widget_3)
        self.tagAsMain = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.tagAsMain.setObjectName("tagAsMain")
        self.verticalLayout_9.addWidget(self.tagAsMain)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 400, 611, 151))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.visGroupNameEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.visGroupNameEntry.setObjectName("visGroupNameEntry")
        self.horizontalLayout_4.addWidget(self.visGroupNameEntry)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.groupLevel = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.groupLevel.setMinimum(1)
        self.groupLevel.setObjectName("groupLevel")
        self.horizontalLayout_4.addWidget(self.groupLevel)
        self.assignVisGroup = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.assignVisGroup.setObjectName("assignVisGroup")
        self.horizontalLayout_4.addWidget(self.assignVisGroup)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_4, "")
        self.space_tab = QtWidgets.QWidget()
        self.space_tab.setObjectName("space_tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.space_tab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.spaceList = QtWidgets.QListWidget(self.space_tab)
        self.spaceList.setObjectName("spaceList")
        self.verticalLayout_12.addWidget(self.spaceList)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spaceUp = QtWidgets.QPushButton(self.space_tab)
        self.spaceUp.setObjectName("spaceUp")
        self.horizontalLayout_8.addWidget(self.spaceUp)
        self.spaceDown = QtWidgets.QPushButton(self.space_tab)
        self.spaceDown.setObjectName("spaceDown")
        self.horizontalLayout_8.addWidget(self.spaceDown)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.spaceQuickButtons = QtWidgets.QGridLayout()
        self.spaceQuickButtons.setObjectName("spaceQuickButtons")
        self.verticalLayout_18.addLayout(self.spaceQuickButtons)
        self.label_17 = QtWidgets.QLabel(self.space_tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.multiWeights = QtWidgets.QTableWidget(self.space_tab)
        self.multiWeights.setEnabled(False)
        self.multiWeights.setColumnCount(2)
        self.multiWeights.setObjectName("multiWeights")
        self.multiWeights.setColumnCount(2)
        self.multiWeights.setRowCount(0)
        self.multiWeights.horizontalHeader().setVisible(False)
        self.verticalLayout_18.addWidget(self.multiWeights)
        self.horizontalLayout_12.addLayout(self.verticalLayout_18)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.space_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuVisibility = QtWidgets.QMenu(self.menuTools)
        self.menuVisibility.setObjectName("menuVisibility")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCard_Orients = QtWidgets.QAction(MainWindow)
        self.actionCard_Orients.setCheckable(True)
        self.actionCard_Orients.setObjectName("actionCard_Orients")
        self.actionReconnect_Real_Joints = QtWidgets.QAction(MainWindow)
        self.actionReconnect_Real_Joints.setObjectName("actionReconnect_Real_Joints")
        self.actionCard_Orients_2 = QtWidgets.QAction(MainWindow)
        self.actionCard_Orients_2.setCheckable(True)
        self.actionCard_Orients_2.setObjectName("actionCard_Orients_2")
        self.actionConnectors = QtWidgets.QAction(MainWindow)
        self.actionConnectors.setCheckable(True)
        self.actionConnectors.setObjectName("actionConnectors")
        self.actionHandles = QtWidgets.QAction(MainWindow)
        self.actionHandles.setCheckable(True)
        self.actionHandles.setObjectName("actionHandles")
        self.actionMatch_Selected_Orients = QtWidgets.QAction(MainWindow)
        self.actionMatch_Selected_Orients.setObjectName("actionMatch_Selected_Orients")
        self.actionNaming_Rules = QtWidgets.QAction(MainWindow)
        self.actionNaming_Rules.setObjectName("actionNaming_Rules")
        self.actionShow_Individual_Restores = QtWidgets.QAction(MainWindow)
        self.actionShow_Individual_Restores.setCheckable(True)
        self.actionShow_Individual_Restores.setObjectName("actionShow_Individual_Restores")
        self.actionShow_Card_Rig_State = QtWidgets.QAction(MainWindow)
        self.actionShow_Card_Rig_State.setCheckable(True)
        self.actionShow_Card_Rig_State.setObjectName("actionShow_Card_Rig_State")
        self.menuVisibility.addAction(self.actionCard_Orients_2)
        self.menuVisibility.addAction(self.actionConnectors)
        self.menuVisibility.addAction(self.actionHandles)
        self.menuTools.addAction(self.actionReconnect_Real_Joints)
        self.menuTools.addAction(self.menuVisibility.menuAction())
        self.menuTools.addAction(self.actionMatch_Selected_Orients)
        self.menuSettings.addAction(self.actionNaming_Rules)
        self.menuSettings.addAction(self.actionShow_Individual_Restores)
        self.menuSettings.addAction(self.actionShow_Card_Rig_State)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.rigStateTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCompat.translate("MainWindow", "MainWindow", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtCompat.translate("MainWindow", "Start", None, -1))
        self.buildBonesBtn.setText(QtCompat.translate("MainWindow", "Build Bones", None, -1))
        self.buildRigBtn.setText(QtCompat.translate("MainWindow", "Build Rig", None, -1))
        self.selectAllBtn.setText(QtCompat.translate("MainWindow", "Select All", None, -1))
        self.deleteRigBtn.setText(QtCompat.translate("MainWindow", "Delete Rig", None, -1))
        self.deleteBonesBtn.setText(QtCompat.translate("MainWindow", "Delete Bones", None, -1))
        self.saveModsBtn.setText(QtCompat.translate("MainWindow", "Save Mods", None, -1))
        self.restoreModsBtn.setText(QtCompat.translate("MainWindow", "Restore Mods", None, -1))
        self.makeCardBtn.setText(QtCompat.translate("MainWindow", "Make Card", None, -1))
        self.rebuildProxyBtn.setText(QtCompat.translate("MainWindow", "Rebuild Proxy", None, -1))
        self.constraintsRestore.setText(QtCompat.translate("MainWindow", "Const", None, -1))
        self.lockedAttrsRestore.setText(QtCompat.translate("MainWindow", "Locked", None, -1))
        self.spacesRestore.setText(QtCompat.translate("MainWindow", "Space", None, -1))
        self.pushButton_3.setText(QtCompat.translate("MainWindow", "Shape", None, -1))
        self.visGroupRestore.setText(QtCompat.translate("MainWindow", "Vis", None, -1))
        self.connectionsRestore.setText(QtCompat.translate("MainWindow", "Conn", None, -1))
        self.setDrivenRestore.setText(QtCompat.translate("MainWindow", "Driven", None, -1))
        self.customAttrsRestore.setText(QtCompat.translate("MainWindow", "Attrs", None, -1))
        self.cardLister.headerItem().setText(0, QtCompat.translate("MainWindow", "Name", None, -1))
        self.cardLister.headerItem().setText(1, QtCompat.translate("MainWindow", "Vis", None, -1))
        self.cardLister.headerItem().setText(2, QtCompat.translate("MainWindow", "Type", None, -1))
        self.cardLister.headerItem().setText(3, QtCompat.translate("MainWindow", "Start", None, -1))
        self.cardLister.headerItem().setText(4, QtCompat.translate("MainWindow", "Repeat", None, -1))
        self.cardLister.headerItem().setText(5, QtCompat.translate("MainWindow", "End", None, -1))
        self.cardLister.headerItem().setText(6, QtCompat.translate("MainWindow", "Mirror", None, -1))
        self.cardLister.headerItem().setText(7, QtCompat.translate("MainWindow", "Side", None, -1))
        self.mergeCardBtn.setText(QtCompat.translate("MainWindow", "Merge", None, -1))
        self.label.setText(QtCompat.translate("MainWindow", "Cards", None, -1))
        self.splitCardBtn.setText(QtCompat.translate("MainWindow", "Split", None, -1))
        self.addCardIkButton.setText(QtCompat.translate("MainWindow", "Add Card Ik", None, -1))
        self.label_2.setText(QtCompat.translate("MainWindow", "Joints", None, -1))
        self.duplicateCardBtn.setText(QtCompat.translate("MainWindow", "Duplicate", None, -1))
        self.remCardIkButton.setText(QtCompat.translate("MainWindow", "Rem Card Ik", None, -1))
        self.insertJointBtn.setText(QtCompat.translate("MainWindow", "Insert Child", None, -1))
        self.addTipBtn.setText(QtCompat.translate("MainWindow", "Add Tip", None, -1))
        self.deleteJointBtn.setText(QtCompat.translate("MainWindow", "Delete", None, -1))
        self.customUpBtn.setText(QtCompat.translate("MainWindow", "Custom Up", None, -1))
        self.jointLister.horizontalHeaderItem(0).setText(QtCompat.translate("MainWindow", "Name", None, -1))
        self.jointLister.horizontalHeaderItem(1).setText(QtCompat.translate("MainWindow", "Helper", None, -1))
        self.jointLister.horizontalHeaderItem(2).setText(QtCompat.translate("MainWindow", "Output", None, -1))
        self.jointLister.horizontalHeaderItem(3).setText(QtCompat.translate("MainWindow", "Handles", None, -1))
        self.jointLister.horizontalHeaderItem(4).setText(QtCompat.translate("MainWindow", "Orient To", None, -1))
        self.jointLister.horizontalHeaderItem(5).setText(QtCompat.translate("MainWindow", "Child Of", None, -1))
        self.cardParams.horizontalHeaderItem(0).setText(QtCompat.translate("MainWindow", "1", None, -1))
        self.cardParams.horizontalHeaderItem(1).setText(QtCompat.translate("MainWindow", "2", None, -1))
        self.updateRigState.setText(QtCompat.translate("MainWindow", "Update", None, -1))
        self.space_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.space_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_2), QtCompat.translate("MainWindow", "Space", None, -1))
        self.vis_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.vis_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_8), QtCompat.translate("MainWindow", "Vis", None, -1))
        self.shape_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.shape_local_load.setText(QtCompat.translate("MainWindow", "Load Local", None, -1))
        self.shape_world_load.setText(QtCompat.translate("MainWindow", "Load World", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_6), QtCompat.translate("MainWindow", "Shape", None, -1))
        self.constraints_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.constraints_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_7), QtCompat.translate("MainWindow", "Const", None, -1))
        self.connections_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.connections_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_5), QtCompat.translate("MainWindow", "Conn", None, -1))
        self.driven_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.driven_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_9), QtCompat.translate("MainWindow", "Driven", None, -1))
        self.custom_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.custom_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_10), QtCompat.translate("MainWindow", "Custom", None, -1))
        self.locked_save.setText(QtCompat.translate("MainWindow", "Save", None, -1))
        self.locked_load.setText(QtCompat.translate("MainWindow", "Load", None, -1))
        self.rigStateTab.setTabText(self.rigStateTab.indexOf(self.tab_11), QtCompat.translate("MainWindow", "Locked", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtCompat.translate("MainWindow", "Cards", None, -1))
        self.label_5.setText(QtCompat.translate("MainWindow", "Shapes", None, -1))
        self.label_11.setText(QtCompat.translate("MainWindow", "Surface Color", None, -1))
        self.label_12.setText(QtCompat.translate("MainWindow", "Curve Color", None, -1))
        self.label_13.setText(QtCompat.translate("MainWindow", "Shapes", None, -1))
        self.label_14.setText(QtCompat.translate("MainWindow", "Shape Clipboard", None, -1))
        self.copyShapes.setText(QtCompat.translate("MainWindow", "Copy to Second Selection", None, -1))
        self.label_7.setText(QtCompat.translate("MainWindow", "Select CVs", None, -1))
        self.select_cvs.setText(QtCompat.translate("MainWindow", "All", None, -1))
        self.copyToCBBtn.setText(QtCompat.translate("MainWindow", "Copy", None, -1))
        self.pasteLocalBtn.setText(QtCompat.translate("MainWindow", "Paste Local", None, -1))
        self.pasteWorldBtn.setText(QtCompat.translate("MainWindow", "Paste World", None, -1))
        self.select_band_edge_1.setText(QtCompat.translate("MainWindow", "Band Edge 1", None, -1))
        self.mirrorShapes.setText(QtCompat.translate("MainWindow", "Mirror to Selected", None, -1))
        self.mirrorSide.setText(QtCompat.translate("MainWindow", "Mirror All to Other Side", None, -1))
        self.select_pin_head.setText(QtCompat.translate("MainWindow", "Pin Head", None, -1))
        self.select_band_edge_2.setText(QtCompat.translate("MainWindow", "Band Edge 2", None, -1))
        self.copyColor.setText(QtCompat.translate("MainWindow", "Copy Color", None, -1))
        self.label_9.setText(QtCompat.translate("MainWindow", "Scale", None, -1))
        self.minus_ten.setText(QtCompat.translate("MainWindow", "-10%", None, -1))
        self.minus_one.setText(QtCompat.translate("MainWindow", "-1%", None, -1))
        self.plus_one.setText(QtCompat.translate("MainWindow", "+1%", None, -1))
        self.plus_ten.setText(QtCompat.translate("MainWindow", "+10%", None, -1))
        self.label_10.setText(QtCompat.translate("MainWindow", "Rotate", None, -1))
        self.rot_local_y.setText(QtCompat.translate("MainWindow", "Rotate Y 45", None, -1))
        self.label_6.setText(QtCompat.translate("MainWindow", "Local", None, -1))
        self.label_8.setText(QtCompat.translate("MainWindow", "World", None, -1))
        self.rot_world_x.setText(QtCompat.translate("MainWindow", "Rotate X 45", None, -1))
        self.rot_local_x.setText(QtCompat.translate("MainWindow", "Rotate X 45", None, -1))
        self.rot_world_y.setText(QtCompat.translate("MainWindow", "Rotate Y 45", None, -1))
        self.rot_local_z.setText(QtCompat.translate("MainWindow", "Rotate Z 45", None, -1))
        self.rot_world_z.setText(QtCompat.translate("MainWindow", "Rotate Z 45", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controller_edit), QtCompat.translate("MainWindow", "Controller Edit", None, -1))
        self.unequipVisControl.setText(QtCompat.translate("MainWindow", "Unequip Vis Control", None, -1))
        self.equipVisControl.setText(QtCompat.translate("MainWindow", "Equip Vis Control", None, -1))
        self.pruneVisGroups.setText(QtCompat.translate("MainWindow", "Prune Unused Vis Groups", None, -1))
        self.tagAsMain.setText(QtCompat.translate("MainWindow", "Tag as Main Control", None, -1))
        self.label_3.setText(QtCompat.translate("MainWindow", "Assign to Group", None, -1))
        self.label_4.setText(QtCompat.translate("MainWindow", "Level", None, -1))
        self.assignVisGroup.setText(QtCompat.translate("MainWindow", "Assign", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtCompat.translate("MainWindow", "Vis Groups", None, -1))
        self.spaceUp.setText(QtCompat.translate("MainWindow", " ^ ", None, -1))
        self.spaceDown.setText(QtCompat.translate("MainWindow", " v ", None, -1))
        self.label_17.setText(QtCompat.translate("MainWindow", "Multi Weights editor (doesn\'t work just yet)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.space_tab), QtCompat.translate("MainWindow", "Space", None, -1))
        self.menuTools.setTitle(QtCompat.translate("MainWindow", "Tools", None, -1))
        self.menuVisibility.setTitle(QtCompat.translate("MainWindow", "Visibility", None, -1))
        self.menuSettings.setTitle(QtCompat.translate("MainWindow", "Settings", None, -1))
        self.actionCard_Orients.setText(QtCompat.translate("MainWindow", "Card Orients", None, -1))
        self.actionReconnect_Real_Joints.setText(QtCompat.translate("MainWindow", "Reconnect Real Joints", None, -1))
        self.actionCard_Orients_2.setText(QtCompat.translate("MainWindow", "Card Orients", None, -1))
        self.actionConnectors.setText(QtCompat.translate("MainWindow", "Connectors", None, -1))
        self.actionHandles.setText(QtCompat.translate("MainWindow", "Joint Handles", None, -1))
        self.actionMatch_Selected_Orients.setText(QtCompat.translate("MainWindow", "Match Selected Orients", None, -1))
        self.actionNaming_Rules.setText(QtCompat.translate("MainWindow", "Naming Rules", None, -1))
        self.actionShow_Individual_Restores.setText(QtCompat.translate("MainWindow", "Show Individual Restores", None, -1))
        self.actionShow_Card_Rig_State.setText(QtCompat.translate("MainWindow", "Show Card Rig State", None, -1))

from pdil.tool.fossil.cardlister import CardLister
from pdil.tool.fossil.cardparams import CardParams
from pdil.tool.fossil.jointlister import JointLister
