# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\MAYA_APP_DIR\fossil\pdil\tool\fossil/ui/rigToolUI.ui'
#
# Created: Sat Apr 13 19:03:51 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from QT_PDIL_vendored import QtCompat, QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 1009)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 90))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 121))
        self.widget_3.setObjectName("widget_3")
        self.jointCount = QtWidgets.QSpinBox(self.widget_3)
        self.jointCount.setGeometry(QtCore.QRect(10, 3, 42, 22))
        self.jointCount.setMinimum(1)
        self.jointCount.setObjectName("jointCount")
        self.cardJointNames = QtWidgets.QLineEdit(self.widget_3)
        self.cardJointNames.setGeometry(QtCore.QRect(60, 3, 113, 20))
        self.cardJointNames.setObjectName("cardJointNames")
        self.makeCardBtn = QtWidgets.QPushButton(self.widget_3)
        self.makeCardBtn.setGeometry(QtCore.QRect(190, 3, 75, 23))
        self.makeCardBtn.setObjectName("makeCardBtn")
        self.selectAllBtn = QtWidgets.QPushButton(self.widget_3)
        self.selectAllBtn.setGeometry(QtCore.QRect(10, 31, 75, 23))
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.deleteBonesBtn = QtWidgets.QPushButton(self.widget_3)
        self.deleteBonesBtn.setGeometry(QtCore.QRect(90, 61, 75, 23))
        self.deleteBonesBtn.setObjectName("deleteBonesBtn")
        self.buildBonesBtn = QtWidgets.QPushButton(self.widget_3)
        self.buildBonesBtn.setGeometry(QtCore.QRect(90, 31, 75, 23))
        self.buildBonesBtn.setObjectName("buildBonesBtn")
        self.saveModsBtn = QtWidgets.QPushButton(self.widget_3)
        self.saveModsBtn.setGeometry(QtCore.QRect(250, 31, 75, 23))
        self.saveModsBtn.setObjectName("saveModsBtn")
        self.buildRigBtn = QtWidgets.QPushButton(self.widget_3)
        self.buildRigBtn.setGeometry(QtCore.QRect(170, 31, 75, 23))
        self.buildRigBtn.setObjectName("buildRigBtn")
        self.restoreModsBtn = QtWidgets.QPushButton(self.widget_3)
        self.restoreModsBtn.setGeometry(QtCore.QRect(250, 61, 75, 23))
        self.restoreModsBtn.setObjectName("restoreModsBtn")
        self.deleteRigBtn = QtWidgets.QPushButton(self.widget_3)
        self.deleteRigBtn.setGeometry(QtCore.QRect(169, 61, 75, 23))
        self.deleteRigBtn.setObjectName("deleteRigBtn")
        self.rebuildProxyBtn = QtWidgets.QPushButton(self.widget_3)
        self.rebuildProxyBtn.setGeometry(QtCore.QRect(430, 3, 81, 23))
        self.rebuildProxyBtn.setObjectName("rebuildProxyBtn")
        self.verticalLayout.addWidget(self.widget_3)
        self.cardLister = CardLister(self.widget_4)
        self.cardLister.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.cardLister.setObjectName("cardLister")
        self.cardLister.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.cardLister)
        self.widget_5 = QtWidgets.QWidget(self.splitter)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_6.setObjectName("widget_6")
        self.duplicateCardBtn = QtWidgets.QPushButton(self.widget_6)
        self.duplicateCardBtn.setGeometry(QtCore.QRect(60, 2, 75, 23))
        self.duplicateCardBtn.setObjectName("duplicateCardBtn")
        self.insertJointBtn = QtWidgets.QPushButton(self.widget_6)
        self.insertJointBtn.setGeometry(QtCore.QRect(60, 32, 75, 23))
        self.insertJointBtn.setObjectName("insertJointBtn")
        self.addTipBtn = QtWidgets.QPushButton(self.widget_6)
        self.addTipBtn.setGeometry(QtCore.QRect(140, 32, 75, 23))
        self.addTipBtn.setObjectName("addTipBtn")
        self.deleteJointBtn = QtWidgets.QPushButton(self.widget_6)
        self.deleteJointBtn.setGeometry(QtCore.QRect(220, 32, 75, 23))
        self.deleteJointBtn.setObjectName("deleteJointBtn")
        self.mergeCardBtn = QtWidgets.QPushButton(self.widget_6)
        self.mergeCardBtn.setGeometry(QtCore.QRect(140, 2, 75, 23))
        self.mergeCardBtn.setObjectName("mergeCardBtn")
        self.splitCardBtn = QtWidgets.QPushButton(self.widget_6)
        self.splitCardBtn.setGeometry(QtCore.QRect(220, 2, 75, 23))
        self.splitCardBtn.setObjectName("splitCardBtn")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_15.setGeometry(QtCore.QRect(320, 2, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_16.setGeometry(QtCore.QRect(400, 2, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setGeometry(QtCore.QRect(10, 37, 46, 13))
        self.label_2.setObjectName("label_2")
        self.customUpBtn = QtWidgets.QPushButton(self.widget_6)
        self.customUpBtn.setGeometry(QtCore.QRect(500, 30, 75, 23))
        self.customUpBtn.setObjectName("customUpBtn")
        self.verticalLayout_2.addWidget(self.widget_6)
        self.jointLister = JointLister(self.widget_5)
        self.jointLister.setColumnCount(6)
        self.jointLister.setObjectName("jointLister")
        self.jointLister.setColumnCount(6)
        self.jointLister.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.jointLister)
        self.verticalLayout_3.addWidget(self.splitter)
        self.widget_2 = QtWidgets.QWidget(self.splitter_2)
        self.widget_2.setMaximumSize(QtCore.QSize(303, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 95))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 95))
        self.widget_8.setObjectName("widget_8")
        self.cardName = QtWidgets.QLabel(self.widget_8)
        self.cardName.setGeometry(QtCore.QRect(10, 0, 151, 20))
        self.cardName.setText("")
        self.cardName.setObjectName("cardName")
        self.cardType = QtWidgets.QLabel(self.widget_8)
        self.cardType.setGeometry(QtCore.QRect(180, 0, 81, 20))
        self.cardType.setText("")
        self.cardType.setObjectName("cardType")
        self.cardDescription = QtWidgets.QLabel(self.widget_8)
        self.cardDescription.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.cardDescription.setText("")
        self.cardDescription.setWordWrap(True)
        self.cardDescription.setObjectName("cardDescription")
        self.verticalLayout_4.addWidget(self.widget_8)
        self.cardParams = CardParams(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardParams.sizePolicy().hasHeightForWidth())
        self.cardParams.setSizePolicy(sizePolicy)
        self.cardParams.setMinimumSize(QtCore.QSize(0, 250))
        self.cardParams.setObjectName("cardParams")
        self.cardParams.setColumnCount(2)
        self.cardParams.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(1, item)
        self.cardParams.horizontalHeader().setVisible(False)
        self.cardParams.horizontalHeader().setStretchLastSection(True)
        self.cardParams.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.cardParams)
        self.verticalLayout_5.addWidget(self.widget_7)
        spacerItem = QtWidgets.QSpacerItem(20, 466, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.controllerEdit = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controllerEdit.sizePolicy().hasHeightForWidth())
        self.controllerEdit.setSizePolicy(sizePolicy)
        self.controllerEdit.setMinimumSize(QtCore.QSize(0, 400))
        self.controllerEdit.setMaximumSize(QtCore.QSize(16777215, 400))
        self.controllerEdit.setObjectName("controllerEdit")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.controllerEdit)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.testLayout = QtWidgets.QVBoxLayout()
        self.testLayout.setObjectName("testLayout")
        self.verticalLayout_6.addLayout(self.testLayout)
        self.verticalLayout_5.addWidget(self.controllerEdit)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.controller_edit = QtWidgets.QWidget()
        self.controller_edit.setObjectName("controller_edit")
        self.shape_container = QtWidgets.QWidget(self.controller_edit)
        self.shape_container.setGeometry(QtCore.QRect(10, 10, 331, 271))
        self.shape_container.setObjectName("shape_container")
        self.label_5 = QtWidgets.QLabel(self.shape_container)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(self.shape_container)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 331, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 329, 239))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shape_chooser = QtWidgets.QGridLayout()
        self.shape_chooser.setObjectName("shape_chooser")
        self.gridLayout_4.addLayout(self.shape_chooser, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.widget_10 = QtWidgets.QWidget(self.controller_edit)
        self.widget_10.setGeometry(QtCore.QRect(10, 490, 331, 191))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minus_ten = QtWidgets.QPushButton(self.widget_10)
        self.minus_ten.setObjectName("minus_ten")
        self.horizontalLayout_3.addWidget(self.minus_ten)
        self.minus_one = QtWidgets.QPushButton(self.widget_10)
        self.minus_one.setObjectName("minus_one")
        self.horizontalLayout_3.addWidget(self.minus_one)
        self.plus_one = QtWidgets.QPushButton(self.widget_10)
        self.plus_one.setObjectName("plus_one")
        self.horizontalLayout_3.addWidget(self.plus_one)
        self.plus_ten = QtWidgets.QPushButton(self.widget_10)
        self.plus_ten.setObjectName("plus_ten")
        self.horizontalLayout_3.addWidget(self.plus_ten)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.rot_local_x = QtWidgets.QPushButton(self.widget_10)
        self.rot_local_x.setObjectName("rot_local_x")
        self.verticalLayout_7.addWidget(self.rot_local_x)
        self.rot_local_y = QtWidgets.QPushButton(self.widget_10)
        self.rot_local_y.setObjectName("rot_local_y")
        self.verticalLayout_7.addWidget(self.rot_local_y)
        self.rot_local_z = QtWidgets.QPushButton(self.widget_10)
        self.rot_local_z.setObjectName("rot_local_z")
        self.verticalLayout_7.addWidget(self.rot_local_z)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.rot_world_x = QtWidgets.QPushButton(self.widget_10)
        self.rot_world_x.setObjectName("rot_world_x")
        self.verticalLayout_9.addWidget(self.rot_world_x)
        self.rot_world_y = QtWidgets.QPushButton(self.widget_10)
        self.rot_world_y.setObjectName("rot_world_y")
        self.verticalLayout_9.addWidget(self.rot_world_y)
        self.rot_world_z = QtWidgets.QPushButton(self.widget_10)
        self.rot_world_z.setObjectName("rot_world_z")
        self.verticalLayout_9.addWidget(self.rot_world_z)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.widget_12 = QtWidgets.QWidget(self.controller_edit)
        self.widget_12.setGeometry(QtCore.QRect(350, 10, 201, 131))
        self.widget_12.setObjectName("widget_12")
        self.label_11 = QtWidgets.QLabel(self.widget_12)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_12)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 29, 181, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.surfaceColorLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.surfaceColorLayout.setContentsMargins(0, 0, 0, 0)
        self.surfaceColorLayout.setObjectName("surfaceColorLayout")
        self.widget_13 = QtWidgets.QWidget(self.controller_edit)
        self.widget_13.setGeometry(QtCore.QRect(350, 150, 201, 131))
        self.widget_13.setObjectName("widget_13")
        self.label_12 = QtWidgets.QLabel(self.widget_13)
        self.label_12.setGeometry(QtCore.QRect(10, 6, 181, 20))
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_13)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 29, 181, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.curveColorLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.curveColorLayout.setContentsMargins(0, 0, 0, 0)
        self.curveColorLayout.setObjectName("curveColorLayout")
        self.widget_9 = QtWidgets.QWidget(self.controller_edit)
        self.widget_9.setGeometry(QtCore.QRect(20, 300, 501, 181))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.copyShapes = QtWidgets.QPushButton(self.widget_11)
        self.copyShapes.setObjectName("copyShapes")
        self.verticalLayout_11.addWidget(self.copyShapes)
        self.mirrorShapes = QtWidgets.QPushButton(self.widget_11)
        self.mirrorShapes.setObjectName("mirrorShapes")
        self.verticalLayout_11.addWidget(self.mirrorShapes)
        self.mirrorSide = QtWidgets.QPushButton(self.widget_11)
        self.mirrorSide.setObjectName("mirrorSide")
        self.verticalLayout_11.addWidget(self.mirrorSide)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.widget_11)
        self.widget_15 = QtWidgets.QWidget(self.widget_9)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_12.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.widget_15)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.copyToCBBtn = QtWidgets.QPushButton(self.widget_15)
        self.copyToCBBtn.setObjectName("copyToCBBtn")
        self.verticalLayout_12.addWidget(self.copyToCBBtn)
        self.pasteLocalBtn = QtWidgets.QPushButton(self.widget_15)
        self.pasteLocalBtn.setObjectName("pasteLocalBtn")
        self.verticalLayout_12.addWidget(self.pasteLocalBtn)
        self.pasteWorldBtn = QtWidgets.QPushButton(self.widget_15)
        self.pasteWorldBtn.setObjectName("pasteWorldBtn")
        self.verticalLayout_12.addWidget(self.pasteWorldBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.widget_15)
        self.widget_14 = QtWidgets.QWidget(self.widget_9)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.widget_14)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.select_cvs = QtWidgets.QPushButton(self.widget_14)
        self.select_cvs.setObjectName("select_cvs")
        self.verticalLayout_8.addWidget(self.select_cvs)
        self.select_pin_head = QtWidgets.QPushButton(self.widget_14)
        self.select_pin_head.setObjectName("select_pin_head")
        self.verticalLayout_8.addWidget(self.select_pin_head)
        self.select_band_edge_1 = QtWidgets.QPushButton(self.widget_14)
        self.select_band_edge_1.setObjectName("select_band_edge_1")
        self.verticalLayout_8.addWidget(self.select_band_edge_1)
        self.select_band_edge_2 = QtWidgets.QPushButton(self.widget_14)
        self.select_band_edge_2.setObjectName("select_band_edge_2")
        self.verticalLayout_8.addWidget(self.select_band_edge_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.widget_14)
        self.controlCardList = QtWidgets.QTreeWidget(self.controller_edit)
        self.controlCardList.setGeometry(QtCore.QRect(580, 40, 271, 631))
        self.controlCardList.setObjectName("controlCardList")
        self.controlCardList.headerItem().setText(0, "1")
        self.controlCardList.header().setVisible(False)
        self.shapeDebug = QtWidgets.QTextEdit(self.controller_edit)
        self.shapeDebug.setEnabled(True)
        self.shapeDebug.setGeometry(QtCore.QRect(10, 690, 841, 231))
        self.shapeDebug.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.shapeDebug.setObjectName("shapeDebug")
        self.tabWidget.addTab(self.controller_edit, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.visGroups = QtWidgets.QListWidget(self.tab_4)
        self.visGroups.setGeometry(QtCore.QRect(10, 10, 256, 311))
        self.visGroups.setObjectName("visGroups")
        self.equipVisControl = QtWidgets.QPushButton(self.tab_4)
        self.equipVisControl.setGeometry(QtCore.QRect(280, 10, 151, 23))
        self.equipVisControl.setObjectName("equipVisControl")
        self.unequipVisControl = QtWidgets.QPushButton(self.tab_4)
        self.unequipVisControl.setGeometry(QtCore.QRect(280, 50, 151, 23))
        self.unequipVisControl.setObjectName("unequipVisControl")
        self.pruneVisGroups = QtWidgets.QPushButton(self.tab_4)
        self.pruneVisGroups.setGeometry(QtCore.QRect(280, 90, 151, 23))
        self.pruneVisGroups.setObjectName("pruneVisGroups")
        self.visGroupNameEntry = QtWidgets.QLineEdit(self.tab_4)
        self.visGroupNameEntry.setGeometry(QtCore.QRect(10, 360, 171, 20))
        self.visGroupNameEntry.setObjectName("visGroupNameEntry")
        self.assignVisGroup = QtWidgets.QPushButton(self.tab_4)
        self.assignVisGroup.setGeometry(QtCore.QRect(280, 360, 151, 23))
        self.assignVisGroup.setObjectName("assignVisGroup")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(11, 340, 251, 16))
        self.label_3.setObjectName("label_3")
        self.groupLevel = QtWidgets.QSpinBox(self.tab_4)
        self.groupLevel.setGeometry(QtCore.QRect(230, 360, 41, 21))
        self.groupLevel.setMinimum(1)
        self.groupLevel.setObjectName("groupLevel")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(194, 362, 31, 16))
        self.label_4.setObjectName("label_4")
        self.tagAsMain = QtWidgets.QPushButton(self.tab_4)
        self.tagAsMain.setGeometry(QtCore.QRect(280, 200, 151, 23))
        self.tagAsMain.setObjectName("tagAsMain")
        self.tabWidget.addTab(self.tab_4, "")
        self.space_tab = QtWidgets.QWidget()
        self.space_tab.setObjectName("space_tab")
        self.tabWidget.addTab(self.space_tab, "")
        self.artist_tools = QtWidgets.QWidget()
        self.artist_tools.setObjectName("artist_tools")
        self.tabWidget.addTab(self.artist_tools, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuVisibility = QtWidgets.QMenu(self.menuTools)
        self.menuVisibility.setObjectName("menuVisibility")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCard_Orients = QtWidgets.QAction(MainWindow)
        self.actionCard_Orients.setCheckable(True)
        self.actionCard_Orients.setObjectName("actionCard_Orients")
        self.actionReconnect_Real_Joints = QtWidgets.QAction(MainWindow)
        self.actionReconnect_Real_Joints.setObjectName("actionReconnect_Real_Joints")
        self.actionCard_Orients_2 = QtWidgets.QAction(MainWindow)
        self.actionCard_Orients_2.setCheckable(True)
        self.actionCard_Orients_2.setObjectName("actionCard_Orients_2")
        self.actionConnectors = QtWidgets.QAction(MainWindow)
        self.actionConnectors.setCheckable(True)
        self.actionConnectors.setObjectName("actionConnectors")
        self.actionHandles = QtWidgets.QAction(MainWindow)
        self.actionHandles.setCheckable(True)
        self.actionHandles.setObjectName("actionHandles")
        self.actionMatch_Selected_Orients = QtWidgets.QAction(MainWindow)
        self.actionMatch_Selected_Orients.setObjectName("actionMatch_Selected_Orients")
        self.menuVisibility.addAction(self.actionCard_Orients_2)
        self.menuVisibility.addAction(self.actionConnectors)
        self.menuVisibility.addAction(self.actionHandles)
        self.menuTools.addAction(self.actionReconnect_Real_Joints)
        self.menuTools.addAction(self.menuVisibility.menuAction())
        self.menuTools.addAction(self.actionMatch_Selected_Orients)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCompat.translate("MainWindow", "MainWindow", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtCompat.translate("MainWindow", "Start", None, -1))
        self.makeCardBtn.setText(QtCompat.translate("MainWindow", "Make Card", None, -1))
        self.selectAllBtn.setText(QtCompat.translate("MainWindow", "Select All", None, -1))
        self.deleteBonesBtn.setText(QtCompat.translate("MainWindow", "Delete Bones", None, -1))
        self.buildBonesBtn.setText(QtCompat.translate("MainWindow", "Build Bones", None, -1))
        self.saveModsBtn.setText(QtCompat.translate("MainWindow", "Save Mods", None, -1))
        self.buildRigBtn.setText(QtCompat.translate("MainWindow", "Build Rig", None, -1))
        self.restoreModsBtn.setText(QtCompat.translate("MainWindow", "Restore Mods", None, -1))
        self.deleteRigBtn.setText(QtCompat.translate("MainWindow", "Delete Rig", None, -1))
        self.rebuildProxyBtn.setText(QtCompat.translate("MainWindow", "Rebuild Proxy", None, -1))
        self.cardLister.headerItem().setText(0, QtCompat.translate("MainWindow", "Name", None, -1))
        self.cardLister.headerItem().setText(1, QtCompat.translate("MainWindow", "Vis", None, -1))
        self.cardLister.headerItem().setText(2, QtCompat.translate("MainWindow", "Type", None, -1))
        self.cardLister.headerItem().setText(3, QtCompat.translate("MainWindow", "Start", None, -1))
        self.cardLister.headerItem().setText(4, QtCompat.translate("MainWindow", "Repeat", None, -1))
        self.cardLister.headerItem().setText(5, QtCompat.translate("MainWindow", "End", None, -1))
        self.cardLister.headerItem().setText(6, QtCompat.translate("MainWindow", "Mirror", None, -1))
        self.cardLister.headerItem().setText(7, QtCompat.translate("MainWindow", "Side", None, -1))
        self.duplicateCardBtn.setText(QtCompat.translate("MainWindow", "Duplicate", None, -1))
        self.insertJointBtn.setText(QtCompat.translate("MainWindow", "Insert", None, -1))
        self.addTipBtn.setText(QtCompat.translate("MainWindow", "Add Tip", None, -1))
        self.deleteJointBtn.setText(QtCompat.translate("MainWindow", "Delete", None, -1))
        self.mergeCardBtn.setText(QtCompat.translate("MainWindow", "Merge", None, -1))
        self.splitCardBtn.setText(QtCompat.translate("MainWindow", "Split", None, -1))
        self.pushButton_15.setText(QtCompat.translate("MainWindow", "Add Card Ik", None, -1))
        self.pushButton_16.setText(QtCompat.translate("MainWindow", "Rem Card Ik", None, -1))
        self.label.setText(QtCompat.translate("MainWindow", "Cards", None, -1))
        self.label_2.setText(QtCompat.translate("MainWindow", "Joints", None, -1))
        self.customUpBtn.setText(QtCompat.translate("MainWindow", "Custom Up", None, -1))
        self.jointLister.horizontalHeaderItem(0).setText(QtCompat.translate("MainWindow", "Name", None, -1))
        self.jointLister.horizontalHeaderItem(1).setText(QtCompat.translate("MainWindow", "Helper", None, -1))
        self.jointLister.horizontalHeaderItem(2).setText(QtCompat.translate("MainWindow", "Output", None, -1))
        self.jointLister.horizontalHeaderItem(3).setText(QtCompat.translate("MainWindow", "Handles", None, -1))
        self.jointLister.horizontalHeaderItem(4).setText(QtCompat.translate("MainWindow", "Orient To", None, -1))
        self.jointLister.horizontalHeaderItem(5).setText(QtCompat.translate("MainWindow", "Child Of", None, -1))
        self.cardParams.horizontalHeaderItem(0).setText(QtCompat.translate("MainWindow", "1", None, -1))
        self.cardParams.horizontalHeaderItem(1).setText(QtCompat.translate("MainWindow", "2", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtCompat.translate("MainWindow", "Cards", None, -1))
        self.label_5.setText(QtCompat.translate("MainWindow", "Shapes", None, -1))
        self.label_9.setText(QtCompat.translate("MainWindow", "Scale", None, -1))
        self.minus_ten.setText(QtCompat.translate("MainWindow", "-10%", None, -1))
        self.minus_one.setText(QtCompat.translate("MainWindow", "-1%", None, -1))
        self.plus_one.setText(QtCompat.translate("MainWindow", "+1%", None, -1))
        self.plus_ten.setText(QtCompat.translate("MainWindow", "+10%", None, -1))
        self.label_10.setText(QtCompat.translate("MainWindow", "Rotate", None, -1))
        self.label_6.setText(QtCompat.translate("MainWindow", "Local", None, -1))
        self.rot_local_x.setText(QtCompat.translate("MainWindow", "Rotate X 45", None, -1))
        self.rot_local_y.setText(QtCompat.translate("MainWindow", "Rotate Y 45", None, -1))
        self.rot_local_z.setText(QtCompat.translate("MainWindow", "Rotate Z 45", None, -1))
        self.label_8.setText(QtCompat.translate("MainWindow", "World", None, -1))
        self.rot_world_x.setText(QtCompat.translate("MainWindow", "Rotate X 45", None, -1))
        self.rot_world_y.setText(QtCompat.translate("MainWindow", "Rotate Y 45", None, -1))
        self.rot_world_z.setText(QtCompat.translate("MainWindow", "Rotate Z 45", None, -1))
        self.label_11.setText(QtCompat.translate("MainWindow", "Surface Color", None, -1))
        self.label_12.setText(QtCompat.translate("MainWindow", "Curve Color", None, -1))
        self.label_13.setText(QtCompat.translate("MainWindow", "Shapes", None, -1))
        self.copyShapes.setText(QtCompat.translate("MainWindow", "Copy to Second Selection", None, -1))
        self.mirrorShapes.setText(QtCompat.translate("MainWindow", "Mirror to Selected", None, -1))
        self.mirrorSide.setText(QtCompat.translate("MainWindow", "Mirror All to Other Side", None, -1))
        self.label_14.setText(QtCompat.translate("MainWindow", "Shape Clipboard", None, -1))
        self.copyToCBBtn.setText(QtCompat.translate("MainWindow", "Copy", None, -1))
        self.pasteLocalBtn.setText(QtCompat.translate("MainWindow", "Paste Local", None, -1))
        self.pasteWorldBtn.setText(QtCompat.translate("MainWindow", "Paste World", None, -1))
        self.label_7.setText(QtCompat.translate("MainWindow", "Select CVs", None, -1))
        self.select_cvs.setText(QtCompat.translate("MainWindow", "All", None, -1))
        self.select_pin_head.setText(QtCompat.translate("MainWindow", "Pin Head", None, -1))
        self.select_band_edge_1.setText(QtCompat.translate("MainWindow", "Band Edge 1", None, -1))
        self.select_band_edge_2.setText(QtCompat.translate("MainWindow", "Band Edge 2", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controller_edit), QtCompat.translate("MainWindow", "Controller Edit", None, -1))
        self.equipVisControl.setText(QtCompat.translate("MainWindow", "Equip Vis Control", None, -1))
        self.unequipVisControl.setText(QtCompat.translate("MainWindow", "Unequip Vis Control", None, -1))
        self.pruneVisGroups.setText(QtCompat.translate("MainWindow", "Prune Unused Vis Groups", None, -1))
        self.assignVisGroup.setText(QtCompat.translate("MainWindow", "Assign", None, -1))
        self.label_3.setText(QtCompat.translate("MainWindow", "Assign to Group", None, -1))
        self.label_4.setText(QtCompat.translate("MainWindow", "Level", None, -1))
        self.tagAsMain.setText(QtCompat.translate("MainWindow", "Tag as Main Control", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtCompat.translate("MainWindow", "Vis Groups", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.space_tab), QtCompat.translate("MainWindow", "Space", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.artist_tools), QtCompat.translate("MainWindow", "Artist Tools", None, -1))
        self.menuTools.setTitle(QtCompat.translate("MainWindow", "Tools", None, -1))
        self.menuVisibility.setTitle(QtCompat.translate("MainWindow", "Visibility", None, -1))
        self.actionCard_Orients.setText(QtCompat.translate("MainWindow", "Card Orients", None, -1))
        self.actionReconnect_Real_Joints.setText(QtCompat.translate("MainWindow", "Reconnect Real Joints", None, -1))
        self.actionCard_Orients_2.setText(QtCompat.translate("MainWindow", "Card Orients", None, -1))
        self.actionConnectors.setText(QtCompat.translate("MainWindow", "Connectors", None, -1))
        self.actionHandles.setText(QtCompat.translate("MainWindow", "Joint Handles", None, -1))
        self.actionMatch_Selected_Orients.setText(QtCompat.translate("MainWindow", "Match Selected Orients", None, -1))

from pdil.tool.fossil.cardlister import CardLister
from pdil.tool.fossil.cardparams import CardParams
from pdil.tool.fossil.jointlister import JointLister
