# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\patc_home_RxMain/RxTools/TechArt\Maya/UI/rigToolUI.ui'
#
# Created: Sun Apr 23 12:40:23 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 947)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtGui.QSplitter(self.tab_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget_4 = QtGui.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtGui.QWidget(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 90))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 121))
        self.widget_3.setObjectName("widget_3")
        self.jointCount = QtGui.QSpinBox(self.widget_3)
        self.jointCount.setGeometry(QtCore.QRect(10, 3, 42, 22))
        self.jointCount.setMinimum(1)
        self.jointCount.setObjectName("jointCount")
        self.cardJointNames = QtGui.QLineEdit(self.widget_3)
        self.cardJointNames.setGeometry(QtCore.QRect(60, 3, 113, 20))
        self.cardJointNames.setObjectName("cardJointNames")
        self.makeCardBtn = QtGui.QPushButton(self.widget_3)
        self.makeCardBtn.setGeometry(QtCore.QRect(190, 3, 75, 23))
        self.makeCardBtn.setObjectName("makeCardBtn")
        self.selectAllBtn = QtGui.QPushButton(self.widget_3)
        self.selectAllBtn.setGeometry(QtCore.QRect(10, 31, 75, 23))
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.deleteBonesBtn = QtGui.QPushButton(self.widget_3)
        self.deleteBonesBtn.setGeometry(QtCore.QRect(90, 61, 75, 23))
        self.deleteBonesBtn.setObjectName("deleteBonesBtn")
        self.buildBonesBtn = QtGui.QPushButton(self.widget_3)
        self.buildBonesBtn.setGeometry(QtCore.QRect(90, 31, 75, 23))
        self.buildBonesBtn.setObjectName("buildBonesBtn")
        self.saveModsBtn = QtGui.QPushButton(self.widget_3)
        self.saveModsBtn.setGeometry(QtCore.QRect(250, 31, 75, 23))
        self.saveModsBtn.setObjectName("saveModsBtn")
        self.buildRigBtn = QtGui.QPushButton(self.widget_3)
        self.buildRigBtn.setGeometry(QtCore.QRect(170, 31, 75, 23))
        self.buildRigBtn.setObjectName("buildRigBtn")
        self.restoreModsBtn = QtGui.QPushButton(self.widget_3)
        self.restoreModsBtn.setGeometry(QtCore.QRect(250, 61, 75, 23))
        self.restoreModsBtn.setObjectName("restoreModsBtn")
        self.deleteRigBtn = QtGui.QPushButton(self.widget_3)
        self.deleteRigBtn.setGeometry(QtCore.QRect(169, 61, 75, 23))
        self.deleteRigBtn.setObjectName("deleteRigBtn")
        self.verticalLayout.addWidget(self.widget_3)
        self.cardLister = CardLister(self.widget_4)
        self.cardLister.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cardLister.setObjectName("cardLister")
        self.verticalLayout.addWidget(self.cardLister)
        self.widget_5 = QtGui.QWidget(self.splitter)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtGui.QWidget(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_6.setObjectName("widget_6")
        self.duplicateCardBtn = QtGui.QPushButton(self.widget_6)
        self.duplicateCardBtn.setGeometry(QtCore.QRect(60, 2, 75, 23))
        self.duplicateCardBtn.setObjectName("duplicateCardBtn")
        self.insertJointBtn = QtGui.QPushButton(self.widget_6)
        self.insertJointBtn.setGeometry(QtCore.QRect(60, 32, 75, 23))
        self.insertJointBtn.setObjectName("insertJointBtn")
        self.addTipBtn = QtGui.QPushButton(self.widget_6)
        self.addTipBtn.setGeometry(QtCore.QRect(140, 32, 75, 23))
        self.addTipBtn.setObjectName("addTipBtn")
        self.deleteJointBtn = QtGui.QPushButton(self.widget_6)
        self.deleteJointBtn.setGeometry(QtCore.QRect(220, 32, 75, 23))
        self.deleteJointBtn.setObjectName("deleteJointBtn")
        self.mergeCardBtn = QtGui.QPushButton(self.widget_6)
        self.mergeCardBtn.setGeometry(QtCore.QRect(140, 2, 75, 23))
        self.mergeCardBtn.setObjectName("mergeCardBtn")
        self.splitCardBtn = QtGui.QPushButton(self.widget_6)
        self.splitCardBtn.setGeometry(QtCore.QRect(220, 2, 75, 23))
        self.splitCardBtn.setObjectName("splitCardBtn")
        self.pushButton_15 = QtGui.QPushButton(self.widget_6)
        self.pushButton_15.setGeometry(QtCore.QRect(320, 2, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtGui.QPushButton(self.widget_6)
        self.pushButton_16.setGeometry(QtCore.QRect(400, 2, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label = QtGui.QLabel(self.widget_6)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.widget_6)
        self.label_2.setGeometry(QtCore.QRect(10, 37, 46, 13))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.widget_6)
        self.jointLister = JointLister(self.widget_5)
        self.jointLister.setColumnCount(6)
        self.jointLister.setObjectName("jointLister")
        self.jointLister.setColumnCount(6)
        self.jointLister.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.jointLister.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.jointLister)
        self.verticalLayout_3.addWidget(self.splitter)
        self.widget_2 = QtGui.QWidget(self.splitter_2)
        self.widget_2.setMaximumSize(QtCore.QSize(303, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtGui.QWidget(self.widget_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_8 = QtGui.QWidget(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 95))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 95))
        self.widget_8.setObjectName("widget_8")
        self.cardName = QtGui.QLabel(self.widget_8)
        self.cardName.setGeometry(QtCore.QRect(10, 0, 151, 20))
        self.cardName.setText("")
        self.cardName.setObjectName("cardName")
        self.cardType = QtGui.QLabel(self.widget_8)
        self.cardType.setGeometry(QtCore.QRect(180, 0, 81, 20))
        self.cardType.setText("")
        self.cardType.setObjectName("cardType")
        self.cardDescription = QtGui.QLabel(self.widget_8)
        self.cardDescription.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.cardDescription.setText("")
        self.cardDescription.setWordWrap(True)
        self.cardDescription.setObjectName("cardDescription")
        self.verticalLayout_4.addWidget(self.widget_8)
        self.cardParams = CardParams(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardParams.sizePolicy().hasHeightForWidth())
        self.cardParams.setSizePolicy(sizePolicy)
        self.cardParams.setMinimumSize(QtCore.QSize(0, 250))
        self.cardParams.setObjectName("cardParams")
        self.cardParams.setColumnCount(2)
        self.cardParams.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cardParams.setHorizontalHeaderItem(1, item)
        self.cardParams.horizontalHeader().setVisible(False)
        self.cardParams.horizontalHeader().setStretchLastSection(True)
        self.cardParams.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.cardParams)
        self.verticalLayout_5.addWidget(self.widget_7)
        spacerItem = QtGui.QSpacerItem(20, 466, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuVisibility = QtGui.QMenu(self.menuTools)
        self.menuVisibility.setObjectName("menuVisibility")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCard_Orients = QtGui.QAction(MainWindow)
        self.actionCard_Orients.setCheckable(True)
        self.actionCard_Orients.setObjectName("actionCard_Orients")
        self.actionReconnect_Real_Joints = QtGui.QAction(MainWindow)
        self.actionReconnect_Real_Joints.setObjectName("actionReconnect_Real_Joints")
        self.actionCard_Orients_2 = QtGui.QAction(MainWindow)
        self.actionCard_Orients_2.setObjectName("actionCard_Orients_2")
        self.actionConnectors = QtGui.QAction(MainWindow)
        self.actionConnectors.setObjectName("actionConnectors")
        self.actionHandles = QtGui.QAction(MainWindow)
        self.actionHandles.setObjectName("actionHandles")
        self.actionMatch_Selected_Orients = QtGui.QAction(MainWindow)
        self.actionMatch_Selected_Orients.setObjectName("actionMatch_Selected_Orients")
        self.menuVisibility.addAction(self.actionCard_Orients_2)
        self.menuVisibility.addAction(self.actionConnectors)
        self.menuVisibility.addAction(self.actionHandles)
        self.menuTools.addAction(self.actionReconnect_Real_Joints)
        self.menuTools.addAction(self.menuVisibility.menuAction())
        self.menuTools.addAction(self.actionMatch_Selected_Orients)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Util", None, QtGui.QApplication.UnicodeUTF8))
        self.makeCardBtn.setText(QtGui.QApplication.translate("MainWindow", "Make Card", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllBtn.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteBonesBtn.setText(QtGui.QApplication.translate("MainWindow", "Delete Bones", None, QtGui.QApplication.UnicodeUTF8))
        self.buildBonesBtn.setText(QtGui.QApplication.translate("MainWindow", "Build Bones", None, QtGui.QApplication.UnicodeUTF8))
        self.saveModsBtn.setText(QtGui.QApplication.translate("MainWindow", "Save Mods", None, QtGui.QApplication.UnicodeUTF8))
        self.buildRigBtn.setText(QtGui.QApplication.translate("MainWindow", "Build Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreModsBtn.setText(QtGui.QApplication.translate("MainWindow", "Restore Mods", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRigBtn.setText(QtGui.QApplication.translate("MainWindow", "Delete Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Vis", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.cardLister.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "Side", None, QtGui.QApplication.UnicodeUTF8))
        self.duplicateCardBtn.setText(QtGui.QApplication.translate("MainWindow", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.insertJointBtn.setText(QtGui.QApplication.translate("MainWindow", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.addTipBtn.setText(QtGui.QApplication.translate("MainWindow", "Add Tip", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteJointBtn.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeCardBtn.setText(QtGui.QApplication.translate("MainWindow", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.splitCardBtn.setText(QtGui.QApplication.translate("MainWindow", "Split", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "Add Card Ik", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow", "Rem Card Ik", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Cards", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Helper", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Handles", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Orient To", None, QtGui.QApplication.UnicodeUTF8))
        self.jointLister.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Child Of", None, QtGui.QApplication.UnicodeUTF8))
        self.cardParams.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cardParams.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Vis Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVisibility.setTitle(QtGui.QApplication.translate("MainWindow", "Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCard_Orients.setText(QtGui.QApplication.translate("MainWindow", "Card Orients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReconnect_Real_Joints.setText(QtGui.QApplication.translate("MainWindow", "Reconnect Real Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCard_Orients_2.setText(QtGui.QApplication.translate("MainWindow", "Card Orients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectors.setText(QtGui.QApplication.translate("MainWindow", "Connectors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHandles.setText(QtGui.QApplication.translate("MainWindow", "Handles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMatch_Selected_Orients.setText(QtGui.QApplication.translate("MainWindow", "Match Selected Orients", None, QtGui.QApplication.UnicodeUTF8))

from motiga.tool.fossil.cardlister import CardLister
from motiga.tool.fossil.jointlister import JointLister
from motiga.tool.fossil.cardparams import CardParams
